//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetHistory
    {
        public int ID { get; set; }
        public string AssetTag { get; set; }
        public string CheckedOutBy { get; set; }
        public System.DateTime CheckedOutDate { get; set; }
        public Nullable<System.DateTime> CheckedInDate { get; set; }
    }
}
